namespace circuitplayground {
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const Boss1_blow_up1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const Boss1_blow_up10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const Boss1_blow_up2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const Boss1_blow_up3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const Boss1_blow_up4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const Boss1_blow_up5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const Boss1_blow_up6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const Boss1_blow_up7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const Boss1_blow_up8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const Boss1_blow_up9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const boom1_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const boom1_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const boom1_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const boom1_4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const boom1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const boom2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const boom3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const boom4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const boss1_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const boss1_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const boss1_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const boss1_4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const boss1_5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const boss1_6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const destroy1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const destroy2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const destroy3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const destroy4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_b1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_b2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_b3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_b4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_c_blow_up1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_c_blow_up2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_c_blow_up3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_c_blow_up4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_c_underattack = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_c1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_c2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_c3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_c4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_d_blow_up1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_d_blow_up2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_d_blow_up3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_d_blow_up4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_d_underattack = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_d1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_d2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_d3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy_d4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy0_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy0_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy0_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy0_4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy1_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy1_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy1_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy1_4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy2__4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy2_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy2_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const enemy2_3 = image.ofBuffer(hex``);
}
